apiVersion: apps/v1
kind: Deployment
metadata:
  name: insighton-ai
  namespace: insighton
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insighton-ai
  template:
    metadata:
      labels:
        app: insighton-ai
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: insighton-ghcr-secret
      containers:
        - name: ai
          image: ghcr.io/nhnacademy-aiot3-insighton/insighton-ai:4aeba08d642969199f85aaa76fe2387ec36108c5
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: insighton-ai-secret
                  key: DB_HOST
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: insighton-ai-secret
                  key: REDIS_HOST
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: insighton-ai-secret
                  key: REDIS_PASSWORD
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: insighton-ai-secret
                  key: GEMINI_API_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: insighton-ai-secret
                  key: DB_PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: insighton-ai-secret
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: insighton-ai-secret
                  key: RABBITMQ_PASSWORD
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: insighton-ai-secret
                  key: INFLUXDB_TOKEN
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 5
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "512Mi"
