apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: insighton-ingress
  namespace: insighton
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - insighton.store
      secretName: insighton-tls
  rules:
    - host: insighton.store
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: insighton-gateway
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: insighton-front
                port:
                  number: 80
