apiVersion: apps/v1
kind: Deployment
metadata:
  name: insighton-actuator-simulator
  namespace: insighton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insighton-actuator-simulator
  template:
    metadata:
      labels:
        app: insighton-actuator-simulator
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: insighton-ghcr-secret
      containers:
        - name: actuator-simulator
          image: ghcr.io/nhnacademy-aiot3-insighton/insighton-actuator-simulator:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "512Mi"
