apiVersion: apps/v1
kind: Deployment
metadata:
  name: insighton-gateway
  namespace: insighton
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insighton-gateway
  template:
    metadata:
      labels:
        app: insighton-gateway
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: insighton-ghcr-secret
      containers:
        - name: api-gateway
          image: ghcr.io/nhnacademy-aiot3-insighton/insighton-gateway:c1f4d849bad01aced4babaf06fb599a9cbc5d07a
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "512Mi"