apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy
  namespace: insighton-logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: alloy-pod-reader
  namespace: insighton
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alloy-pod-reader
  namespace: insighton
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alloy-pod-reader
subjects:
  - kind: ServiceAccount
    name: alloy
    namespace: insighton-logging
