apiVersion: v1
kind: Service
metadata:
  name: insighton-auth
  namespace: insighton
spec:
  selector:
    app: insighton-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
