apiVersion: v1
kind: Service
metadata:
  name: insighton-redis-telemetry
  namespace: insighton
spec:
  selector:
    app: insighton-redis-telemetry
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
