apiVersion: apps/v1
kind: Deployment
metadata:
  name: insighton-config
  namespace: insighton
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insighton-config
  template:
    metadata:
      labels:
        app: insighton-config
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: insighton-ghcr-secret
      containers:
        - name: config
          image: ghcr.io/nhnacademy-aiot3-insighton/insighton-config:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: CONFIG_GITHUB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: CONFIG_GITHUB_USERNAME
            - name: CONFIG_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: CONFIG_GITHUB_TOKEN
            - name: CONFIG_REPO_URI
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: CONFIG_REPO_URI
            - name: CONFIG_SERVER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: CONFIG_SERVER_USERNAME
            - name: CONFIG_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: CONFIG_SERVER_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "512Mi"
