apiVersion: v1
kind: Service
metadata:
  name: insighton-influxdb
  namespace: insighton
spec:
  selector:
    app: insighton-influxdb
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP
