apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: insighton-ruleengine
  namespace: insighton
spec:
  serviceName: insighton-ruleengine-headless
  replicas: 2
  selector:
    matchLabels:
      app: insighton-ruleengine
  template:
    metadata:
      labels:
        app: insighton-ruleengine
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: insighton-ghcr-secret
      containers:
        - name: ruleengine
          image: ghcr.io/nhnacademy-aiot3-insighton/insighton-ruleengine:b279d1359244ca5c16a899ee70652cb37e51e770
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: insighton-ruleengine-secret
                  key: DB_HOST
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: insighton-ruleengine-secret
                  key: DB_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: insighton-ruleengine-secret
                  key: REDIS_HOST
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: insighton-ruleengine-secret
                  key: REDIS_PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: insighton-ruleengine-secret
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: insighton-ruleengine-secret
                  key: RABBITMQ_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "512Mi"
