apiVersion: v1
kind: Service
metadata:
  name: insighton-ruleengine
  namespace: insighton
spec:
  selector:
    app: insighton-ruleengine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
