apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: insighton-logging
data:
  loki.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.insighton-logging.svc.cluster.local:3100
        isDefault: true
        editable: false
      - name: Kubernetes API
        type: yesoreyeram-infinity-datasource
        access: proxy
        jsonData:
          auth_method: bearerToken
          tlsSkipVerify: true
          allowedHosts:
            - https://kubernetes.default.svc
        secureJsonData:
          bearerToken: $GRAFANA_K8S_TOKEN
        editable: false
