apiVersion: apps/v1
kind: Deployment
metadata:
  name: insighton-zipkin
  namespace: insighton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insighton-zipkin
  template:
    metadata:
      labels:
        app: insighton-zipkin
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      containers:
        - name: zipkin
          image: openzipkin/zipkin:latest
          ports:
            - containerPort: 9411
          readinessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "512Mi"
