apiVersion: v1
kind: Service
metadata:
  name: insighton-zipkin
  namespace: insighton
spec:
  selector:
    app: insighton-zipkin
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
  type: ClusterIP
